'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class monitorednodes
    
    '''<summary>
    '''frmMonitoredNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMonitoredNodes As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''hdnTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTitle As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectMonitoredNodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectMonitoredNodeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectSecurityTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectSecurityTool As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectInstance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectInstance As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectDomain As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectIP As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelecthostname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelecthostname As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectfqdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectfqdn As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectPort As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectPath As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectUseFqdnInsteadOfIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectUseFqdnInsteadOfIP As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectIsTlsEncryted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectIsTlsEncryted As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelectMonitoringLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectMonitoringLevel As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereSecurityTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereSecurityTool As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereInstance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereInstance As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereDomain As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereIP As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWherehostname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWherehostname As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWherefqdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWherefqdn As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWherePort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWherePort As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWherePath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWherePath As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereUseFqdnInsteadOfIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereUseFqdnInsteadOfIP As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereIsTlsEncryted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereIsTlsEncryted As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnWhereMonitoringLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnWhereMonitoringLevel As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSort As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtSecurityTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurityTool As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dlstSecurityTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlstSecurityTool As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtInstance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInstance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dlstInstance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlstInstance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDomain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dlstDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlstDomain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txthostname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthostname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtfqdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfqdn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPort As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPath As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cblUseFqdnInsteadOfIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblUseFqdnInsteadOfIP As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cblIsTlsEncryted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblIsTlsEncryted As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cblMonitoringLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblMonitoringLevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSubmitInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitInput As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelInput As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cblOrder01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder01 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder01 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder02 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder02 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder03 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder03 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder04 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder04 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder05 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder05 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder06 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder06 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder07 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder07 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder08 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder08 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder09 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder09 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder10 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder10 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblOrder11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOrder11 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''descOrder11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descOrder11 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSubmitSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitSort As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSort As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gridMonitoredNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridMonitoredNodes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnFrst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFrst As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrev As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLast As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtRowCountPerPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRowCountPerPage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTotalRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRowCount As Global.System.Web.UI.WebControls.Label
End Class
